Repository graphql/express-graphql, pull requests merged in 2020-05, with the labels that each got.

#591 TS: Allow to pass object as graphiql option
  types/index.d.ts
Labels: PR: bug fix 🐞

#599 Use fixed versions for all devDependencies
  package.json
  yarn.lock
Labels: PR: dependency 📦

#601 Update prettier
  .prettierrc
  README.md
  package.json
  resources/build.js
  resources/gen-changelog.js
  resources/utils.js
  src/__tests__/http-test.js
  src/index.js
  types/test.ts
  yarn.lock
Labels: PR: dependency 📦

#602 Update flow
  .flowconfig
  package.json
  src/index.js
  yarn.lock
Labels: PR: dependency 📦

#603 Update flow
  .travis.yml
  package.json
Labels: PR: dependency 📦

#604 resources: sync up with 'graphql-js' scripts
  resources/build.js
  resources/gen-changelog.js
  resources/utils.js
Labels: PR: internal 🏠

#606 babel: Switch to using `babel-env`
  .babelrc.json
  package.json
  yarn.lock
Labels: PR: internal 🏠

#607 Switch to null coalescing operator
  src/__tests__/http-test.js
  src/index.js
  src/parseBody.js
Labels: PR: polish 💅
