Repository graphql/express-graphql, pull requests merged in 2020-06, with the labels that each got.

#608 Do not pass parameters if we can't parse them.
  src/index.js
  types/index.d.ts
Labels: PR: breaking change 💥

#609 Make few check more explicit
  src/index.js
Labels: PR: polish 💅

#611 Convert all throwed errors to `httpError`
  src/index.js
Labels: PR: polish 💅

#613 Rewrite code to fully use async/await
  .flowconfig
  src/__tests__/http-test.js
  src/index.js
  src/renderGraphiQL.js
Labels: PR: polish 💅

#614 Update GraphiQL and its deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#615 Update 'graphql-js'
  package.json
  src/__tests__/http-test.js
  types/index.d.ts
  yarn.lock
Labels: PR: dependency 📦

#616 Update TS deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#617 Sync ESLint with 'graphql-js'
  .eslintrc.yml
  package.json
  src/__tests__/http-test.js
  src/__tests__/usage-test.js
  src/index.js
  src/parseBody.js
  yarn.lock
Labels: PR: polish 💅

#618 TS: enable linting on types
  .eslintrc.yml
  package.json
  types/index.d.ts
  types/test.ts
Labels: PR: polish 💅

#619 ESLint: sync 'eslint-internal-rules' with 'graphql-js'
  .eslintrc.yml
  package.json
  resources/eslint-internal-rules/README.md
  resources/eslint-internal-rules/index.js
  resources/eslint-internal-rules/no-dir-import.js
  resources/eslint-internal-rules/package.json
  yarn.lock
Labels: PR: internal 🏠

#620 Migrate from legacy API to URLSearchParams
  .eslintrc.yml
  .mocharc.yml
  src/__tests__/http-test.js
  src/index.js
Labels: PR: polish 💅

#621 package.json: sync with `graphql-js`
  package.json
Labels: PR: internal 🏠

#623 Update deps
  .eslintrc.yml
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#624 Flow cleanup typings
  src/index.js
  src/parseBody.js
  src/renderGraphiQL.js
Labels: PR: breaking change 💥

#622 Sync TS typings with Flow typings
  types/index.d.ts
Labels: PR: breaking change 💥

#626 Convert CommonJS module syntax to ES6
  README.md
  src/__tests__/http-test.js
  src/__tests__/usage-test.js
  src/index.js
  types/index.d.ts
  types/test.ts
Labels: PR: breaking change 💥

#629 Fix type for extensions option
  src/index.js
  types/index.d.ts
Labels: PR: bug fix 🐞

#631 http-test: clean up framework specific wrappers
  src/__tests__/http-test.js
Labels: PR: polish 💅

#632 Simplify getGraphQLParams
  src/index.js
Labels: PR: polish 💅

#633 http-test: simplify a bit
  src/__tests__/http-test.js
Labels: PR: polish 💅

#634 Switch to NPM
  package-lock.json
  package.json
  yarn.lock
Labels: PR: internal 🏠

#635 Switch to GitHub Actions
  .github/workflows/ci.yml
  .travis.yml
  README.md
Labels: PR: internal 🏠

#636 Swith from coveralls to codecov
  .github/workflows/ci.yml
  .nycrc.yml
  README.md
  codecov.yml
  package-lock.json
  package.json
Labels: PR: internal 🏠

#637 Replace 'dtslint' with TS integration test
  .eslintrc.yml
  .github/workflows/ci.yml
  .gitignore
  integrationTests/README.md
  integrationTests/integration-test.js
  integrationTests/ts/index.ts
  integrationTests/ts/package.json
  integrationTests/ts/test.js
  integrationTests/ts/tsconfig.json
  package-lock.json
  package.json
  tsconfig.json
Labels: PR: internal 🏠

#638 Drop support for TS < 3.4
  integrationTests/ts/package.json
  types/index.d.ts
Labels: PR: breaking change 💥

#639 Sync up .gitignore with 'graphql-js'
  .gitignore
Labels: PR: internal 🏠

#642 Switch to alternative format for type imports
  .eslintrc.yml
  src/__tests__/http-test.js
  src/index.js
  src/parseBody.js
  src/renderGraphiQL.js
Labels: PR: polish 💅

#641 Fix supertest usage inside tests
  src/__tests__/http-test.js
Labels: PR: polish 💅

#645 Modify file upload test
  src/__tests__/http-test.js
Labels: PR: polish 💅

#644 nyc: remove unused exclude config option
  .nycrc.yml
Labels: PR: internal 🏠

#640 Convert tests to TS
  .eslintrc.yml
  .mocharc.yml
  package-lock.json
  package.json
  src/__tests__/http-test.ts
  src/__tests__/usage-test.ts
  tsconfig.json
Labels: PR: polish 💅
