Repository graphql/express-graphql, pull requests merged in 2020-07, with the labels that each got.

#649 Update README to show how to disable introspection
  README.md
Labels: PR: docs 📝

#650 Improve test coverage
  .DS_Store
  src/__tests__/http-test.ts
Labels: PR: polish 💅

#651 workflows: check commit for ignored files
  .DS_Store
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#652 Update deps
  .eslintrc.yml
  .flowconfig
  package-lock.json
  package.json
Labels: PR: dependency 📦

#653 Allow `extensions` callback to return `undefined`
  src/__tests__/http-test.ts
  src/index.d.ts
  src/index.js
Labels: PR: feature 🚀

#654 nyc: require 100% coverage
  .nycrc.yml
  package.json
Labels: PR: internal 🏠

#655 ESLint: enable 'no-promise-executor-return' check
  .eslintrc.yml
Labels: PR: internal 🏠

#656 Sync up config files with 'graphql-js'
  .eslintignore
  .eslintrc.yml
  .prettierignore
  examples/index.js
  package.json
Labels: PR: internal 🏠

#659 Update graphqlMiddleware and parseBody
  src/index.js
  src/parseBody.js
Labels: PR: polish 💅

#657 ESLint: enable checking of 'examples' dir
  .eslintrc.yml
  examples/index.js
Labels: PR: polish 💅

#661 Add cspell checker
  .babelrc.json
  README.md
  cspell.json
  package-lock.json
  package.json
  resources/checkgit.sh
  resources/load-statically-from-npm.js
  src/__tests__/http-test.ts
  src/renderGraphiQL.js
Labels: PR: polish 💅

#662 Sync up GitHub actions with 'graphql-js'
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#663 Move showStats function to utils
  resources/build.js
  resources/utils.js
Labels: PR: internal 🏠

#664 Update GraphiQL and expose 'headerEditorEnabled' property
  README.md
  examples/index.js
  package-lock.json
  package.json
  src/renderGraphiQL.d.ts
  src/renderGraphiQL.js
Labels: PR: feature 🚀

#666 Fix NPM package on Node10
  .babelrc.json
Labels: PR: bug fix 🐞

#669 Move cspell to devDependencies
  package-lock.json
  package.json
Labels: PR: bug fix 🐞

#670 Update ignore files to ignore only top-level files
  .eslintignore
  .gitignore
  .prettierignore
Labels: PR: internal 🏠

#671 Isolate integration tests from repository
  .eslintignore
  .gitignore
  .prettierignore
  cspell.json
  integrationTests/integration-test.js
  integrationTests/ts/package.json
Labels: PR: internal 🏠

#673 Improve return type of `customFormatErrorFn`
  integrationTests/ts/package.json
  package-lock.json
  package.json
  src/__tests__/http-test.ts
  src/index.d.ts
  src/index.js
  src/renderGraphiQL.d.ts
  src/renderGraphiQL.js
Labels: PR: breaking change 💥

#674 Fix sending of custom headers
  src/renderGraphiQL.js
Labels: PR: bug fix 🐞

#658 Convert remaining files to TypeScript
  .eslintrc.yml
  .mocharc.yml
  cspell.json
  examples/index.ts
  package-lock.json
  package.json
  resources/build.js
  resources/load-statically-from-npm.js
  resources/register.js
  src/index.d.ts
  src/index.ts
  src/parseBody.d.ts
  src/parseBody.ts
  src/renderGraphiQL.d.ts
  src/renderGraphiQL.ts
  tsconfig.json
Labels: PR: polish 💅

#676 Cleanup from Flow and Babel
  .babelrc.json
  .eslintrc.yml
  .flowconfig
  integrationTests/integration-test.js
  integrationTests/ts/test.js
  package-lock.json
  package.json
  resources/build.js
  resources/eslint-internal-rules/index.js
  resources/eslint-internal-rules/no-dir-import.js
  resources/gen-changelog.js
  resources/load-statically-from-npm.js
  resources/utils.js
  tsconfig.json
Labels: PR: internal 🏠

#677 Improve TS type coverage
  .eslintrc.yml
  src/index.ts
  src/parseBody.ts
Labels: PR: polish 💅
