Repository graphql/express-graphql, pull requests merged in 2020-11, with the labels that each got.

#707 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
  resources/build.js
Labels: PR: dependency 📦

#708 build: change to 'build' to 'build:npm'
  .github/workflows/ci.yml
  package.json
  resources/build-npm.js
Labels: PR: internal 🏠

#709 CI: test on node 15
  .github/workflows/ci.yml
  integrationTests/node/package.json
Labels: PR: internal 🏠

#710 TS: Add more checks/validations into 'tsconfig.json'
  tsconfig.json
Labels: PR: internal 🏠

#711 integrationTests: sync with graphql-js
  integrationTests/integration-test.js
Labels: PR: internal 🏠

#712 build: add support for experimental releases
  resources/build-npm.js
Labels: PR: internal 🏠

#713 ESLint: enable more checks
  .eslintrc.yml
  resources/build-npm.js
  resources/gen-changelog.js
  src/index.ts
  src/parseBody.ts
Labels: PR: polish 💅

#714 Update deps
  package-lock.json
  package.json
Labels: PR: dependency 📦

#715 Use HTTP code of underlying errors
  src/__tests__/http-test.ts
  src/parseBody.ts
Labels: PR: bug fix 🐞

#716 Wrap HttpError into GraphQLError
  .eslintrc.yml
  src/__tests__/http-test.ts
  src/index.ts
  src/parseBody.ts
Labels: PR: bug fix 🐞

#717 test: log TS errors but run tests
  resources/register.js
Labels: PR: internal 🏠

#718 Switch to using 'devAssert' similar to `graphql-js`
  .eslintrc.yml
  src/index.ts
Labels: PR: polish 💅

#722 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#723 Run tests before release
  package.json
Labels: PR: internal 🏠

#583 Support for experimental @defer & @stream
  integrationTests/ts/package.json
  package-lock.json
  package.json
  src/__tests__/http-test.ts
  src/__tests__/isAsyncIterable-test.ts
  src/index.ts
  src/isAsyncIterable.ts
Labels: PR: feature 🚀

#724 package.json: move test run to `version` script
  package.json
Labels: PR: internal 🏠

#727 Add instuctions for using experimental features
  README.md
Labels: PR: docs 📝

#725 Update deps
  integrationTests/ts/package.json
  package-lock.json
  package.json
  tsconfig.json
Labels: PR: dependency 📦
