Repository graphql/express-graphql, pull requests merged in 2022-11, with the labels that each got.

#809 Update `README` code references
  README.md
Labels: PR: docs 📝

#796 support default graphiql header state
  README.md
  src/renderGraphiQL.ts
Labels: PR: feature 🚀

#765 Update Node and TypeScript versions in tests
  .github/workflows/ci.yml
  integrationTests/node/package.json
  integrationTests/ts/package.json
Labels: PR: internal 🏠
